"""Emit ordinary R with runtime guards around the declared implementation."""

from pathlib import Path
import re

from normalize_syntax import normalize_syntax
from read_source import Binding


RUNTIME = Path(__file__).with_name("runtime") / "irk-runtime.R"


def emit_r(binding: Binding) -> str:
    implementation_name = ".irk_impl_" + binding.name.replace(".", "_")
    implementation = normalize_syntax(binding.implementation)
    implementation = re.sub(
        rf"^\s*{re.escape(binding.name)}\s*<-",
        f"{implementation_name} <-",
        implementation,
        count=1,
    )

    runtime = RUNTIME.read_text(encoding="utf-8").rstrip()
    return f"""# Generated by IRK.
# The noun/type claim is guarded. The verb relation is not yet proved.

{runtime}

{implementation}

{binding.name} <- function({binding.argument}) {{
    irk_expect_kind({binding.argument}, \"{binding.input_kind}\",
                    \"{binding.name} argument\")
    result <- {implementation_name}({binding.argument})
    irk_expect_kind(result, \"{binding.output_kind}\",
                    \"{binding.name} result\")
    result
}}
"""
